### PR TITLE
Fix in AsseticServiceProvider

### PR DESCRIPTION
**Pull request by radmen**
There was a typo - when `config.path_to_source` was set value of `config.options.path_to_source` was assigned to `$app['assetic.path_to_source']`.

### CODE REVIEW

**Comment by radmen** [comment]
Btw, `path_to_source` could be mentioned in config file :)

**Comment by barryvdh** [comment]
Yeah you are right. I didn't mention it, because I think most people don't need that option, as the source is the same as the web dir. But maybe that is an incorrect assumption.

**Comment by barryvdh** [comment]
I added it to the config (but disabled), so it should be more obvious it can be changed.

**Comment by radmen** [comment]
> Yeah you are right. I didn't mention it, because I think most people don't need that option, as the source is the same as the web dir. But maybe that is an incorrect assumption.

Maybe I was doing something wrong but when my assets where in web dir Assetic compiled files and saved them in the same directory making huge mess.

I'm used to having assets in `app/assets/` and compiling them to web dir (i can put it in .gitignore and forget about them).

**Comment by barryvdh** [comment]
Okay I usually have my assets in public, ie public/img, public/style, public/js and then just set the output name to a different dir (style/style.less -> assetic/style.css). But when everything goes through Assetic, you could probably just as well store the source files outside the web dir I guess.

**Pull request merged**
